name: CI

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Checkout asdf project
      run: git clone https://github.com/asdf-vm/asdf.git
    - name: Activate asdf
      run: source asdf/asdf.sh
    - name: Show env vars 
      run: env
    - name: Test plugin
      env:
        GITHUB_REPOSITORY: ${{ GITHUB_REPOSITORY }}
      run: |
        env
        asdf plugin-test kubectl https://github.com/${GITHUB_REPOSITORY}.git

